/**
 * perfis-api-map.js — de qual página cada prefixo de API depende.
 *
 * ARQUIVO GERADO por `node scripts/gerar-mapa-api.js`. Não editar à mão: o que
 * precisa de ajuste manual é o bloco COMPLEMENTO daquele script.
 *
 * O gate de páginas (perfis-acesso.js) fecha a navegação; sem isto a API
 * continuaria aberta a quem soubesse o endereço do endpoint. A regra: um perfil
 * restrito pode chamar /api/<prefixo> se tiver acesso a ALGUMA das páginas
 * listadas aqui para esse prefixo.
 *
 * Prefixo fora deste arquivo é NEGADO (fail-closed, decisão de 2026-08-19).
 * Consequência que precisa ficar dita: rota nova sem entrada aqui quebra a tela
 * de quem tem perfil restrito. Quando acontecer, o servidor loga
 * '[RBAC] prefixo sem mapa: /api/xxx' — é esse log que diz o que falta.
 *
 * Fora do mapa DE PROPÓSITO (não é esquecimento):
 *   /api/backup, /api/versao, /api/debug  — já são requireRole(['admin'])
 *   /api/proxy                            — proxy genérico de saída
 *   /api/chat-ia, /api/kanban             — nenhuma tela atual os inclui
 *   /api/feriados                         — sem tela consumidora
 */

// Passam sempre: autenticação, preferências do próprio usuário, o que a sidebar
// precisa em toda página, e as rotas públicas (portal do cliente, loja, landing,
// control plane) que ficam antes da barreira de auth.
const LIBERADOS = [
  '/api/login', '/api/logout', '/api/change-password', '/api/auth',
  '/api/user', '/api/usuarios', '/api/perfis', '/api/features',
  '/api/estabelecimentos', '/api/estabelecimento-ativo',
  '/api/admin', '/api/landing', '/api/webhooks', '/api/portal', '/api/orcamento',
  '/api/electron', '/api/cotacao-publica', '/api/me', '/api/eu',
  '/api/orcamento-publico',   // link público do orçamento — auth é o token na URL
  '/api/carrinho', '/api/pedido', '/api/nfses', '/api/dashboard', '/api/loja',
];

// prefixo -> páginas do menu que legitimamente o consomem
const MAPA = {
  '/api/adiantamentos':          ['aprovacoes', 'contas-a-pagar', 'contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'fin-adiantamentos', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/admin':                  ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/adquirentes':            ['adquirentes-cartao', 'aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/agenda':                 ['agenda'],
  '/api/alcadas':                ['aprovacoes', 'config-alcadas'],
  '/api/alertas':                ['notificacoes'],
  '/api/analise':                ['analises-ia', 'config-ia', 'grupos-palavras'],
  '/api/audit-log':              ['auditoria'],
  '/api/auth':                   ['tokens'],
  '/api/bairros':                ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/bi':                     ['consulta', 'inteligencia', 'sugestao-produto'],
  '/api/bll':                    ['bll-monitor', 'bll-proposta', 'bll-salas'],
  '/api/bnc':                    ['bnc-monitor', 'bnc-proposta', 'bnc-salas', 'lances'],
  '/api/boleto-provedores':      ['contas-financeiras'],
  '/api/boletos':                ['contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'fin-lotes-pagamento', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/carrinho':               ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/cartoes':                ['fin-cartoes'],
  '/api/centros-custo':          ['aprovacoes', 'centros-custo', 'contas-a-pagar', 'contas-a-receber', 'contratos', 'crm-funil', 'dre', 'equipamentos', 'ordens-servico', 'os-relatorios', 'patrimonio-bens', 'pedidos-compra'],
  '/api/cep':                    ['estabelecimentos', 'minha-empresa'],
  '/api/certificado':            ['minha-empresa'],
  '/api/cfops':                  ['aprovacoes', 'cadastro-cfops', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/cfops-entrada-map':      ['cadastro-cfops'],
  '/api/cfops-regras':           ['cadastro-cfops'],
  '/api/chamar-garcom':          ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/chat':                   ['comprasnet-monitor'],
  '/api/cnpj':                   ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estabelecimentos', 'estoque-reservas', 'minha-empresa', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pessoas', 'produtos', 'ssl-certificados'],
  '/api/cobrancas':              ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'cobrancas', 'cobrancas-config', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contas-a-receber', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/comissoes':              ['comissoes'],
  '/api/comm':                   ['conversas'],
  '/api/compras':                ['aprovacoes', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/comprasnet':             ['comprasnet-monitor', 'relatorio-participacoes'],
  '/api/conciliacao':            ['conciliacao-bancaria', 'fin-conciliacao-regras'],
  '/api/conexao':                ['conexoes'],
  '/api/config':                 ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'conexoes', 'config-ia', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/contabilidade':          ['ctb-balancete', 'ctb-contabilizacao', 'ctb-lancamentos', 'ctb-plano'],
  '/api/contas-a-pagar':         ['aprovacoes', 'contas-a-pagar', 'fin-adiantamentos', 'fin-lotes-pagamento', 'fin-renegociacoes'],
  '/api/contas-a-receber':       ['contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'fin-adiantamentos', 'fin-renegociacoes', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/contas-financeiras':     ['adquirentes-cartao', 'aprovacoes', 'comissoes', 'conciliacao-bancaria', 'contas-a-pagar', 'contas-a-receber', 'contas-financeiras', 'contratos', 'cp-recorrencias', 'crm-funil', 'equipamentos', 'fin-adiantamentos', 'fin-conciliacao-regras', 'fin-lotes-pagamento', 'fluxo-caixa', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/contratos':              ['aprovacoes', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'estoque-reservas', 'loja', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/conversas':              ['conversas'],
  '/api/cotacao-publica':        ['compras-cotacoes'],
  '/api/cotacoes':               ['compras-cotacoes'],
  '/api/cp-categorias':          ['aprovacoes', 'contas-a-pagar', 'cp-recorrencias'],
  '/api/cp-recorrencias':        ['cp-recorrencias'],
  '/api/cr-categorias':          ['contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/credenciais':            ['consulta', 'propostas-api'],
  '/api/crm':                    ['agenda', 'crm-funil'],
  '/api/cte':                    ['cte'],
  '/api/dashboard':              ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/depositos':              ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque', 'estoque-analises', 'estoque-depositos', 'estoque-inventario', 'estoque-movimentacoes', 'estoque-requisicoes', 'estoque-reservas', 'estoque-transferencias', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/devolucoes':             ['devolucoes'],
  '/api/dre':                    ['dre'],
  '/api/electron':               ['conexoes', 'lances'],
  '/api/emails':                 ['email-log'],
  '/api/equipamentos':           ['equipamentos', 'ordens-servico', 'os-relatorios'],
  '/api/estabelecimentos':       ['contas-financeiras', 'estabelecimentos', 'fiscal-configuracao', 'habilitacao-certidoes', 'usuarios'],
  '/api/estoque':                ['aprovacoes', 'contas-a-pagar', 'devolucoes', 'estoque', 'estoque-analises', 'estoque-lotes', 'estoque-movimentacoes', 'manifestador'],
  '/api/etiquetas':              ['catalogo-etiquetas'],
  '/api/eu':                     ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/farmacia':               ['farmacia-cmed', 'farmacia-config', 'farmacia-medicamentos', 'farmacia-receitas', 'farmacia-sngpc'],
  '/api/faturas':                ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'faturas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/features':               ['meu-perfil', 'minha-empresa'],
  '/api/financeiro':             ['cobrancas-config', 'contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/fiscal':                 ['apuracao-icms', 'apuracao-ipi', 'apuracao-piscofins', 'apuracao-sn', 'cadastro-servicos', 'classificacao', 'classificacao-lote', 'defis', 'fiscal-arquivamento', 'fiscal-diagnostico', 'fiscal-ibscbs', 'livro-caixa', 'retencoes', 'tabelas-fiscais'],
  '/api/fiscal-regras':          ['regras-tributarias'],
  '/api/fluxo-caixa':            ['fluxo-caixa'],
  '/api/fornecedor':             ['devolucoes', 'minha-empresa', 'propostas-api'],
  '/api/fornecedor-integracoes': ['pessoas'],
  '/api/fornecedores':           ['aprovacoes', 'comercial-vendas-perdidas', 'compras-cotacoes', 'contas-a-pagar', 'contratos', 'cp-recorrencias', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-lotes', 'estoque-reservas', 'fin-adiantamentos', 'fin-renegociacoes', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pessoas', 'produtos', 'ssl-certificados'],
  '/api/fornecedores-documentos':['pessoas'],
  '/api/funcionarios':           ['funcionarios', 'producao-apontamento', 'romaneios'],
  '/api/gerencial':              ['fin-orcamento'],
  '/api/gnre':                   ['fiscal-gnre'],
  '/api/govbr':                  ['minha-empresa'],
  '/api/grupos-palavras':        ['consulta', 'grupos-palavras', 'inteligencia'],
  '/api/habilitacao':            ['comprasnet-monitor', 'habilitacao-certidoes', 'relatorio-participacoes'],
  '/api/ia':                     ['conversas'],
  '/api/ifood':                  ['restaurante-ifood'],
  '/api/importacao':             ['importacao'],
  '/api/integracao-tipos':       ['integracao-tipos'],
  '/api/integracoes':            ['integracoes'],
  '/api/interesse':              ['consulta', 'interesse', 'status'],
  '/api/interesses':             ['consulta'],
  '/api/inventarios':            ['estoque-inventario'],
  '/api/itens':                  ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/lance':                  ['blitz', 'lances', 'propostas-api'],
  '/api/landing':                ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/licitacoes':             ['comprasnet-monitor', 'consulta', 'propostas-api', 'relatorio-participacoes'],
  '/api/lida':                   ['consulta'],
  '/api/lidas':                  ['consulta'],
  '/api/locacao':                ['locacao-calendario', 'locacao-config', 'locacao-itens', 'locacao-locacoes', 'locacao-manutencao', 'locacao-painel', 'locacao-tarifas'],
  '/api/login':                  ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/logout':                 ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/loja':                   ['loja', 'loja-config'],
  '/api/lotes':                  ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque', 'estoque-lotes', 'estoque-movimentacoes', 'estoque-reservas', 'estoque-serial', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/lotes-pagamento':        ['fin-lotes-pagamento'],
  '/api/marketplaces':           ['marketplaces'],
  '/api/mdfe':                   ['mdfe'],
  '/api/me':                     ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/metas':                  ['comercial-metas'],
  '/api/mp':                     ['contas-a-receber'],
  '/api/necessidades-compra':    ['compras-necessidades'],
  '/api/nf-avulsa':              ['notas-fiscais', 'nova-nota'],
  '/api/nfce':                   ['fiscal-configuracao', 'notas-fiscais', 'pdv'],
  '/api/nfe':                    ['faturas', 'fiscal-configuracao', 'fiscal-inutilizacao'],
  '/api/nfe-entrada':            ['aprovacoes', 'contas-a-pagar', 'devolucoes', 'manifestador'],
  '/api/nfse':                   ['email-log', 'fiscal-configuracao', 'nfse', 'notas-fiscais'],
  '/api/nfses':                  ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/notas-fiscais':          ['devolucoes', 'notas-fiscais'],
  '/api/optica':                 ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'lentes-indices', 'lentes-materiais', 'lentes-tipos', 'lentes-tratamentos', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'produtos', 'receitas-opticas', 'ssl-certificados'],
  '/api/orcamento':              ['contratos', 'crm-funil', 'equipamentos', 'fin-orcamento', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/orgaos':                 ['agenda', 'consulta', 'interesse', 'sem-interesse'],
  '/api/os':                     ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'ordens-servico', 'os-notificacoes', 'os-relatorios', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/os-tipos':               ['cadastro-os-tipos', 'ordens-servico'],
  '/api/patrimonio':             ['patrimonio-bens'],
  '/api/pcp':                    ['pcp-monitor', 'pcp-proposta', 'pcp-salas'],
  '/api/pdf':                    ['propostas-api'],
  '/api/pdv':                    ['pdv', 'pdv-config'],
  '/api/pedido':                 ['aprovacoes', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'pedidos', 'pedidos-compra', 'portal-credenciais', 'receitas-opticas', 'ssl-certificados'],
  '/api/pedidos':                ['aprovacoes', 'cadastro-cfops', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'comercial-vendas-perdidas', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'loja', 'notas-fiscais', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pedidos-pdv', 'portal-credenciais', 'receitas-opticas', 'romaneios', 'ssl-certificados'],
  '/api/pedidos-compra':         ['aprovacoes', 'comercial-vendas-perdidas', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/perfis':                 ['perfis'],
  '/api/pessoas':                ['aprovacoes', 'comercial-vendas-perdidas', 'comissoes', 'contas-a-receber', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'fin-adiantamentos', 'fin-renegociacoes', 'locacao-locacoes', 'nfse', 'nova-nota', 'ordens-servico', 'os-relatorios', 'pdv', 'pedidos', 'pedidos-compra', 'pedidos-pdv', 'pessoas', 'portal-credenciais', 'producao-projetos', 'receitas-opticas', 'recorrencias', 'ssl-certificados'],
  '/api/plano-contas':           ['aprovacoes', 'contas-a-pagar', 'contas-a-receber', 'contratos', 'crm-funil', 'equipamentos', 'fin-conciliacao-regras', 'fin-orcamento', 'ordens-servico', 'os-relatorios', 'pedidos-compra', 'plano-contas'],
  '/api/politicas-prazo':        ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pdv-config', 'pedidos', 'pedidos-compra', 'pessoas', 'politicas-prazo', 'ssl-certificados'],
  '/api/portal':                 ['portal-credenciais'],
  '/api/posto':                  ['posto-estrutura', 'posto-lmc', 'posto-pista', 'posto-recebimento'],
  '/api/precos':                 ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/producao':               ['producao-apontamento', 'producao-config', 'producao-expedicao', 'producao-fichas', 'producao-ordens', 'producao-painel', 'producao-patio', 'producao-projetos', 'producao-qualidade', 'producao-recursos'],
  '/api/produto-lookup':         ['cadastro-categorias', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'devolucoes', 'produtos'],
  '/api/produto-match':          ['lances'],
  '/api/produtos':               ['aprovacoes', 'cadastro-categorias', 'cadastro-cores', 'cadastro-generos', 'cadastro-marcas', 'cadastro-materiais', 'cadastro-modelos', 'cadastro-os-tipos', 'cadastro-servicos', 'catalogo-etiquetas', 'comercial-tabelas-preco', 'comercial-vendas-perdidas', 'comissoes', 'compras-cotacoes', 'compras-necessidades', 'compras-sugestao', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque', 'estoque-lotes', 'estoque-movimentacoes', 'estoque-requisicoes', 'estoque-reservas', 'estoque-serial', 'estoque-transferencias', 'loja', 'loja-config', 'notas-fiscais', 'nova-nota', 'ordens-montagem', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pedidos-pdv', 'portal-credenciais', 'producao-fichas', 'produtos', 'receitas-opticas', 'restaurante-cardapio', 'restaurante-ficha', 'ssl-certificados'],
  '/api/proposta':               ['consulta', 'propostas-api'],
  '/api/propostas':              ['propostas-api'],
  '/api/provisoes':              ['fin-provisoes'],
  '/api/recorrencias':           ['recorrencias'],
  '/api/relatorio-concorrentes': ['relatorio-lances'],
  '/api/relatorio-lances':       ['relatorio-lances'],
  '/api/relatorios':             ['relatorio-participacoes'],
  '/api/renegociacoes':          ['fin-renegociacoes'],
  '/api/requisicoes':            ['estoque-requisicoes'],
  '/api/reservas':               ['estoque-reservas'],
  '/api/restaurante':            ['restaurante-caixa', 'restaurante-cardapio', 'restaurante-config', 'restaurante-delivery', 'restaurante-ficha', 'restaurante-gorjetas', 'restaurante-indicadores', 'restaurante-kds', 'restaurante-painel-retirada', 'restaurante-salao'],
  '/api/rh':                     ['comissoes', 'funcionarios'],
  '/api/robo':                   ['conexoes', 'integracoes'],
  '/api/romaneios':              ['romaneios'],
  '/api/sc':                     ['conexoes', 'integracoes'],
  '/api/sem-interesse':          ['consulta', 'sem-interesse'],
  '/api/serial':                 ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque', 'estoque-movimentacoes', 'estoque-reservas', 'estoque-serial', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/servicos':               ['cadastro-servicos', 'contratos', 'crm-funil', 'equipamentos', 'ordens-servico', 'os-relatorios', 'pedidos-compra'],
  '/api/smtp':                   ['email'],
  '/api/sniper':                 ['blitz', 'health-comprasnet', 'lances', 'propostas-api', 'relatorio-participacoes', 'timing-analise', 'tokens'],
  '/api/ssl':                    ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-agenda', 'ssl-certificados', 'ssl-integracao'],
  '/api/status':                 ['status'],
  '/api/sync':                   ['agenda', 'consulta', 'interesse', 'sem-interesse', 'status'],
  '/api/tabelas-preco':          ['aprovacoes', 'comercial-tabelas-preco', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pessoas', 'ssl-certificados'],
  '/api/tarefas':                ['conexoes'],
  '/api/tef':                    ['tef'],
  '/api/telegram':               ['comprasnet-monitor'],
  '/api/timeline-lances':        ['relatorio-lances'],
  '/api/tipos-operacao':         ['aprovacoes', 'cadastro-cfops', 'cadastro-os-tipos', 'cadastro-tipos-operacao', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'notas-fiscais', 'nova-nota', 'ordens-servico', 'os-relatorios', 'pdv-config', 'pedidos', 'pedidos-compra', 'regras-tributarias', 'ssl-certificados'],
  '/api/transferencias':         ['estoque-transferencias'],
  '/api/transportadoras':        ['aprovacoes', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/user':                   ['meu-perfil'],
  '/api/usuarios':               ['aprovacoes', 'auditoria', 'comercial-metas', 'comercial-vendas-perdidas', 'comissoes', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'meu-perfil', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'pessoas', 'ssl-certificados', 'usuarios'],
  '/api/valores-proposta':       ['propostas-api'],
  '/api/vendas-perdidas':        ['aprovacoes', 'comercial-metas', 'comercial-vendas-perdidas', 'contratos', 'crm-funil', 'devolucoes', 'equipamentos', 'estoque-reservas', 'ordens-servico', 'os-relatorios', 'pedidos', 'pedidos-compra', 'ssl-certificados'],
  '/api/wa-campanhas':           ['conversas'],
  '/api/whatsapp':               ['conversas'],
};

module.exports = { LIBERADOS, MAPA };
